compatibility_date = "2024-09-21"
workers_dev = false
logpush = true

<<<<<<< Updated upstream
<<<<<<< Updated upstream
tail_consumers = [
  {service = "travelese-tail"},
  {service = "engine-tail"}
]
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes

[env.production]
name = "engine"
route = { pattern = "engine.travelese.xyz/*", zone_name = "travelese.xyz" }

kv_namespaces = [
  { binding = "KV", id = "b321b928d84747a4b899b21894a720c2" }
]

mtls_certificates = [
  { binding = "TELLER_CERT", certificate_id = "44d6feaf-8445-414a-a096-151a21a16988" }
]

r2_buckets = [
  { binding = "STORAGE", bucket_name = "engine-assets", preview_bucket_name = ""}
]

[env.staging]
name = "engine-staging"
route = { pattern = "engine-staging.travelese.xyz/*", zone_name = "travelese.xyz" }

kv_namespaces = [
  { binding = "KV", id = "b321b928d84747a4b899b21894a720c2" }
]

mtls_certificates = [
  { binding = "TELLER_CERT", certificate_id = "44d6feaf-8445-414a-a096-151a21a16988" }
]

r2_buckets = [
  { binding = "STORAGE", bucket_name = "engine-assets", preview_bucket_name = "" }
]
