compatibility_date = "2024-09-21"
workers_dev = false
logpush = true

[env.production]
name = "engine"
route = { pattern = "engine.travelese.ai/*", zone_name = "travelese.ai" }

kv_namespaces = [
  { binding = "KV", id = "b321b928d84747a4b899b21894a720c2" }
]

mtls_certificates = [
  { binding = "TELLER_CERT", certificate_id = "44d6feaf-8445-414a-a096-151a21a16988" }
]

r2_buckets = [
  { binding = "STORAGE", bucket_name = "engine-assets", preview_bucket_name = ""}
]

[env.staging]
name = "engine-staging"
route = { pattern = "engine-staging.travelese.ai/*", zone_name = "travelese.ai" }

kv_namespaces = [
  { binding = "KV", id = "b321b928d84747a4b899b21894a720c2" }
]

mtls_certificates = [
  { binding = "TELLER_CERT", certificate_id = "44d6feaf-8445-414a-a096-151a21a16988" }
]

r2_buckets = [
  { binding = "STORAGE", bucket_name = "engine-assets", preview_bucket_name = "" }
]

[observability]
enabled = true