name: Preview Deployment - Website
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_WEBSITE }}
  TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  TURBO_TEAM: ${{ secrets.VERCEL_ORG_ID }}
on:
  push:
    branches-ignore:
      - main
    paths:
      - apps/website/**
      - packages/**
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Check environment variables
        run: |
          echo "NEXT_PUBLIC_SUPABASE_URL is set: ${{ env.NEXT_PUBLIC_SUPABASE_URL != '' }}"
          echo "SUPABASE_SERVICE_ROLE_KEY is set: ${{ env.SUPABASE_SERVICE_ROLE_KEY != '' }}"
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      # - name: 🔦 Run linter
      #   run: bun run lint --filter=@travelese/website
      # - name: 🪐 Check TypeScript
      #   run: bun run typecheck --filter=@travelese/website
      - name: 📤 Pull Vercel Environment Information
        run: bunx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: 🏗 Build Project Artifacts
        run: bunx vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: bunx vercel deploy --prebuilt --archive=tgz --token=${{ secrets.VERCEL_TOKEN }}
